// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alolksttyxnvbkewjbnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsb2xrc3R0eXhudmJrZXdqYm53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDQyMjAsImV4cCI6MjA2NzI4MDIyMH0.66l8ORoW7E0DC4cClHOddK-kwSg_jo74uofQ4ogMom8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});